### ISSUE TITLE
CTRTransfer 2.1.0 Step #3 Error

### ISSUE THREAD

**Issue by sthetix** [d0k3/Decrypt9WIP#94] opened 2016-09-17 17:17 UTC
Hello, when using ctrtransfer , it always failed at step #3. How can I solve this?
I am using the latest decrypt9wip
I have tried different SD Card but still the same.

NAND size : 1,954,545,664 bytes (Samsung NAND)
Downgraded to 9.2 from 10.7 successfully without errors at the end.

```
Initializing SD card... success
Build: Decrypt9WIP (2016/08/23)
Work directory: /files9
Game directory: /files9
sector0x96 Key: otp.bin not found
0x03 KeyX & KeyY: already set up
0x05 KeyY: already set up
0x25 KeyX: already set up
0x18 KeyX: already set up
0x1B KeyX: loaded, verified, set up
0x24 KeyY: automatically set up
Finalizing Initialization...

Initialization: success!

You selected [Auto CTRNAND Transfer].

This feature writes to the SysNAND.
This may overwrite important data!

If you wish to proceed, enter:
<Left>, <Up>, <Right>, <Up>, <A>

(B to return, START to reboot)

Selected: [Auto CTRNAND Transfer]
A9LH not detected, checking FIRM0...
Select CTRNAND transfer image
Use arrow keys and <A> to choose a file
2.1.0-4U_ctrtransfer_o3ds.bin
Image size is: 794624000 byte

Step #0: Optional NAND backup
Press <B> to skip and continue without backup
Dumping SysNAND. Size (MB): 1240
Use arrow keys and <A> to choose a name
NANDmin.bin
Creating NANDmin.bin ...
NAND dump SHA256: B5798252...
Store to NANDmin.bin.sha: ok

Step #1: .SHA verification of CTRNAND image...
Checking hash from .SHA file...
Step #1 success!

Step #2: Dumping transfer files
Searching for SecureInfo_A...
Found at 0E788000, size 273b
Creating B95C44CF_SecureInfo_A ...
Searching for movable.sed...
Found at 0E748000, size 320b
Creating B95C44CF_movable.sed ...
Searching for LocalFriendCodeSeed_B...
Found at 0E6D0000, size 272b
Creating B95C44CF_LocalFriendCodeSeed_B ...
Searching for configsave.bin...
Found at 0F258000, size 256kB
Creating B95C44CF_configsave.bin ...
Step #2 success!

Step #3: Injecting CTRNAND transfer image
Switching out NAND header first...
Auto CTRNAND Transfer: failed!

Press B to return, START to reboot.
```

**Comment by ihaveamac** [comment] 2016-09-18 16:41
after testing this out, I think it's failing here, after adding a debug message. 

https://github.com/d0k3/Decrypt9WIP/blob/b9fa44764219d31e6edffb679461496c3b80c7c6/source/decryptor/transfer.c#L135

**Comment by ihaveamac** [comment] 2016-09-18 16:56
looks like the NAND header isn't getting replaced, after dumping it from NAND. I could be wrong though...

**Comment by d0k3** [comment] 2016-09-18 19:53
Can you try this test build, @sthetix?
https://transfer.sh/KRUPb/decrypt9wip-20160918-195245.zip

**Comment by d0k3** [comment] 2016-09-18 20:10
And, one more thing. One thing that could help me is you dumping your NAND header (D9 can do it) before and after the failed transfer. Upload somewhere, show me.

**Comment by sthetix** [comment] 2016-09-18 23:06
Still the same error:

```
Initializing SD card... success
Build: Decrypt9WIP (2016/09/18)
Work directory: /files9
Game directory: /files9
sector0x96 Key: otp.bin not found
0x03 KeyX & KeyY: already set up
0x05 KeyY: already set up
0x25 KeyX: already set up
0x18 KeyX: already set up
0x1B KeyX: loaded, verified, set up
0x24 KeyY: automatically set up
Finalizing Initialization...

Initialization: success!

You selected [Forced CTRNAND Transfer].

This feature writes to the SysNAND.
This may overwrite important data!

If you wish to proceed, enter:
<Left>, <Up>, <Right>, <Up>, <A>

(B to return, START to reboot)

Selected: [Forced CTRNAND Transfer]
A9LH not detected, checking FIRM0...
Select CTRNAND transfer image
Use arrow keys and <A> to choose a file
2.1.0-4U_ctrtransfer_o3ds.bin
Image size is: 794624000 byte
Forced transfer, not checking region

Step #0: Optional NAND backup
Press <B> to skip and continue without backup
Dumping SysNAND. Size (MB): 1240
Use arrow keys and <A> to choose a name
(cancelled by user)

Step #1: .SHA verification of CTRNAND image...
Forced transfer, skipping this step
Step #1 skipped

Step #2: Dumping transfer files
Searching for SecureInfo_A...
Found at 0E788000, size 273b
Creating B95C44CF_SecureInfo_A ...
Searching for movable.sed...
Found at 0E748000, size 320b
Creating B95C44CF_movable.sed ...
Searching for LocalFriendCodeSeed_B...
Found at 0E6D0000, size 272b
Creating B95C44CF_LocalFriendCodeSeed_B ...
Searching for configsave.bin...
Found at 0F258000, size 256kB
Creating B95C44CF_configsave.bin ...
Step #2 success!

Step #3: Injecting CTRNAND transfer image
Switching out NAND header first...
Forced CTRNAND Transfer: failed!

Press B to return, START to reboot.
```

**Nand header**  

https://transfer.sh/Ks0uc/nand-hdr.bin

**Comment by d0k3** [comment] 2016-09-19 11:38
Alright. Well, what happens here is, D9 should write the NAND header, but it does not. If anything goes wrong, there should at least be an error code, and even that is not there. Meaning: your hardware may be special.

What we need to do now is make sure D9 is actually able to write to your system at all. So... can you confirm this? You could, f.e. restore an earlier NAND backup and check if it is actually written.

**Comment by sthetix** [comment] 2016-09-19 11:46
Yesterday, I successfully restored the console back to 10.7.0-32U using decrypt9wip.

**Comment by d0k3** [comment] 2016-09-19 11:49
Alright, maybe just the header area is problematic (that area does not get changed in a standard restore). Maybe you can join us on IRC freenode #Cakey and we can try to find a solution together?

**Comment by sthetix** [comment] 2016-09-19 22:32
I can confirm that the nand header area is locked (not rewriteable) so ctrtransfer always failed.
In mean time, i think there is no solution for this issue.

**Comment by sthetix** [comment] 2016-09-20 15:55
I found an interesting article about nand locking
[tn2976_mt29f_boot_blocking.pdf](https://github.com/d0k3/Decrypt9WIP/files/483045/tn2976_mt29f_boot_blocking.pdf)

**Comment by d0k3** [comment] 2016-09-20 16:25
Alright... I will close this issue here now, cause this is clearly not a D9 issue but a very specific hardware quirk instead. Join us on #Cakey to find a solution for this. The issue won't help a lot.

**Comment by MelonGx** [comment] 2016-09-30 01:26
This is interesting.
This type of new NAND chip appeared earlier from the CTRNAND transfer method --- The Super Famicom exclusive New3DSLL, which used this type of new NAND chip, released on early Aug 2016.
So I'm wondering about how it can prevent a hacking method in the future.

**Comment by MelonGx** [comment] 2016-10-09 08:24
@d0k3 @sthetix 
From some Chinese hackers' oral report, they had succeeded CTRNAND transferring several New3DSes with the 1.82GB New Samsung NAND chip.
That's to say, if they did tell the truth, then not all the 1.82GB New Samsung NAND chip have the header lock.

**Comment by sthetix** [comment] 2016-10-09 09:27
@MelonGx Thx for the info. Right now i dont have access to that console. I
sold it :)
But I will buy a newer New 3DS XL to find out and retest.

**Comment by d0k3** [comment] 2016-10-10 09:34
Just saying, N3DS don't need to be downgraded anymore anyways, so this issue hast lost relevancy anyways. I am also unsure if write blocks to the header are actually intentional or just a quirk of this specific unit.

**Comment by sthetix** [comment] 2016-10-10 09:37
yes. thx for that info @d0k3

**Comment by Jerry-Shaw** [comment] 2017-03-12 03:50
@d0k3 , sorry to disturb. But I actually met the same problem on one of my friends' N3DS on 9.2. Since the guide of otpless has been taken off, is there any way to finish A9LH?

**Comment by d0k3** [comment] 2017-03-12 10:46
Alright, reopening this. OTPless is no more recommended because it has a ~3% bricking risk (I may be wrong with that number, don't hit me @stuckpixel).

Can you provide us with the log? Also, is this N3DS hardmodded (or, can you do a hardmod in case something goes wrong?) and open for some experiments?

If you can partiticipate in some experiments, it may make sense for you to join us on freenode @Cakey to discuss this.

**Comment by Jerry-Shaw** [comment] 2017-03-12 11:52
Actually, my friend is not in the same province with me right now. I'll talk to her later see if she is willing to do it. 

I just taught her to go back to Menuhax, the SD card has been formatted, logs are gone. But here is the photo taken when 2.1 transfer went failed.
![qq 20170312193619](https://cloud.githubusercontent.com/assets/13212198/23831402/49614dd0-075b-11e7-94d9-54adecff31fd.jpg)

I found an old guide somewhere about OTPless method and tried. But the file "firm1.bin" mismatched always and failed. Doing this made the firm0 on console corrupted, which was found when we tried to do a 2.1 transfer again. Luckily, the console can be booted as always and we managed to restore the original NAND backup to normal. And we still got an error "Switching out NAND header first..." when transferring to 2.1 under Plailect's guide.

The N3DS is JPN. The size of the NAND backup file is 1 979 711 488 byte, on 9.2.0-20J. All checks passed on downgrade checker. Everything seems good.

**Comment by cakey** [comment] 2017-03-13 20:05
Ah! That's why I'm getting notified :)

**Comment by david-zzj** [comment] 2017-03-14 09:50
i have the same issues, please help !!!!

**Comment by d0k3** [comment] 2017-03-14 10:44
@david-zzj - please provide me with more information. Is this a JPN console? Also, where does it freeze, and can you provide me with a log?

**Comment by Jerry-Shaw** [comment] 2017-03-14 11:53
@d0k3 Hey, I just talked with my friend. She is going to stay in Menuhax right now. And if she has time after work, she can do the 2.1 transferring again and provide the log.

**Comment by d0k3** [comment] 2017-03-14 23:04
Everyone having this issue can also try the D9 build from 20161113 (found on the releases page). This may be worth a try.

**Comment by d0k3** [comment] 2017-03-14 23:05
Also, to get really behind this, I'd need someone who (a) is willing to help testing and (b) has a hardmod installed in his console.

**Comment by david-zzj** [comment] 2017-03-15 06:39
i am glad to do some testing for you.

**Comment by d0k3** [comment] 2017-03-15 11:20
That means you have a (J) console and a hardmod? And, is the issue you have exactly the same as the one that is shown in @Jerry-Shaw's photo?

**Comment by david-zzj** [comment] 2017-03-15 14:32
yes，the same issue.

**Comment by d0k3** [comment] 2017-03-16 18:25
@david-zzj - can you try this test build and tell me the last output you see then?
https://transfer.sh/hKUqu/decrypt9wip-20170316-182505.zip

**Comment by david-zzj** [comment] 2017-03-17 03:06
yesterday when I try the "force ctrnand transfer" option , it worked !!!








--------------------------------------------------------------------------------









 
 发件人: d0k3  <notifications@github.com>
 

 
 发送时间: 2017-03-17 02:25:36
 

 
 收件人:d0k3/Decrypt9WIP <decrypt9wip@noreply.github.com> 

 
 抄送:钟志机 <13560104970@139.com>,Mention <mention@noreply.github.com> 

 
 主题: Re: [d0k3/Decrypt9WIP] CTRTransfer 2.1.0 Step #3 Error (#94)
 



@david-zzj - can you try this test build and tell me the last output you see then?
 https://transfer.sh/hKUqu/decrypt9wip-20170316-182505.zip

**Comment by Jerry-Shaw** [comment] 2017-03-17 05:14
@david-zzj "force ctrnand transfer" worked without bricking console if the head needs to be switching out? Did you tried the normal transfer method?

**Comment by d0k3** [comment] 2017-03-17 16:28
@david-zzj - that should only have an effect for N3DS type transferables. What kind of transferable did you provide?

**Comment by d0k3** [comment] 2017-03-18 16:17
Everyone having trouble with the CTRNAND transfer in D9 - could you try [SafeCtrTransfer](https://github.com/d0k3/SafeCtrTransfer)? Test build here:
https://transfer.sh/FkkeT/safectrtransfer-20170318-161317.zip

Instructions are found in the link. In case something goes wrong (this is tested, but unreleased), SafeCtrTransfer provides options for recovery. Something going wrong is unlikely, tho.

**Comment by Jerry-Shaw** [comment] 2017-03-18 23:56
I'll tell my friend to try it and wait for the result.

**Comment by d0k3** [comment] 2017-03-20 00:17
It could also make sense to try the latest D9 hourly from here:
https://d0k3.secretalgorithm.com/

**Comment by Jerry-Shaw** [comment] 2017-03-20 03:17
I told her of the new version but she seems to be busy recently. When she tries, we'll get result.

**Comment by Jerry-Shaw** [comment] 2017-04-24 12:10
Hi, my friend sold her console, so, there might be no possibility to reproduce the issue and make further tests. We may close the issue or just leave it open?

**Comment by d0k3** [comment] 2017-05-16 10:10
Okay, closing this now. We do have SafeCtrTransfer, which is now the recommended way of doing things.

**Closed by d0k3** 2017-05-16 10:10 UTC
