### ISSUE TITLE
A unique issue of Safehax/D9WIP's Auto CTRNAND Transfer on JPN 2DS (20161113 OK but 20170130/0214 NG, unable to reproduce this issue currently)

### ISSUE THREAD

**Issue by MelonGx** [d0k3/Decrypt9WIP#162] opened 2017-03-01 16:32 UTC
The 2DS has 1.84GB NAND chip & NAND validation failure.
(But since the old version can do the CTRNAND Transfer successfully, I don't think the NAND type & the NAND validation are the problem.)

On Safehax/20170130:
![1](https://cloud.githubusercontent.com/assets/7697767/23469473/aae0c0ca-fede-11e6-93dc-59545e7909f3.jpg)
It interrupted and outputed this immediately.

On Safehax/20170214:
![2](https://cloud.githubusercontent.com/assets/7697767/23469906/f9524c5a-fedf-11e6-94ab-ee70ff9b71c1.jpg)
It could be processed to this seedsave.bin step, but froze on it.

On Safehax/20161113:
The CTRNAND Transfer was successfully completed.

I don't know why the old version is OK but the recent versions doesn't.
If it can be fixed on next version .....

**Comment by d0k3** [comment] 2017-03-01 20:38
Okay, well, I'm stumbling in the dark right now. I do wonder, though, on that screenshot you made for the 20170214 version, the CMACs seem to be already fixed - that's rather strange, cause they never are in an image provided with the guide(tm). Did you perhaps make these transferables yourself? Did you ever try with any official ones?

**Comment by MelonGx** [comment] 2017-03-02 06:56
>make these transferables myself
Yes.

>try with any official ones
You mean System Transfer or D9WIP releases but not nightlies?

**Comment by d0k3** [comment] 2017-03-02 09:25
I mean the CTRtransfer images provided by @Plailect. I have a suspicion something goes wrong here because of your transferables. If there is no trouble with the ones Plailect provides, I'd like to take a look at your transferables (if that is okay for you, we can discuss that on temp or IRC and I'd give you instructions on what personal data to remove).

**Comment by MelonGx** [comment] 2017-03-06 10:43
No, they don't fail on older version, but fail at newer version.

**Comment by MelonGx** [comment] 2017-03-06 10:49
Oh, I'm sorry but wait a minute, what does your "transferables" actually mean?
I checked I had no missed/damaged files & no wrong steps on CTRNAND transferring.

**Comment by d0k3** [comment] 2017-03-07 01:27
By trannsferable I mean the ~1GB CTRNAND file you are using for the transfer. It is not one of @Plailect's, right?

**Comment by d0k3** [comment] 2017-03-10 12:49
@MelonGx - I need more info to get this solved. Did you use Plailect's transferable or ones of your own. Also read what I wrote before!

**Comment by MelonGx** [comment] 2017-03-16 09:58
@d0k3 It does be Plailect's.

**Comment by d0k3** [comment] 2017-03-18 16:18
@MelonGx well... maybe you could try [SafeCtrTransfer](https://github.com/d0k3/SafeCtrTransfer)? Test build here:
https://transfer.sh/FkkeT/safectrtransfer-20170318-161317.zip

Instructions are found in the link. In case something goes wrong (this is tested, but unreleased), SafeCtrTransfer provides options for recovery. Something going wrong is unlikely, though.

And I'm still clueless abotu what could cause this.

**Comment by d0k3** [comment] 2017-03-20 00:16
And, also recommended, try the latest D9 hourly from here:
https://d0k3.secretalgorithm.com/

**Comment by MelonGx** [comment] 2017-03-21 11:34
Since the 2DS has been successfully CTR-transferred by 20161113 release & has returned to the owner, I am not able to test that console again .....

**Comment by d0k3** [comment] 2017-03-21 12:20
Okay, I suggest we close this issue then, as we can't resolve it. There is still that other issue open, and the reason behing is most likely the same. What do you think?

**Comment by Jerry-Shaw** [comment] 2017-03-21 12:22
@d0k3 , seems like version 20161113 worked. Have you got any idea about "switching header out" in the new version? Not sure about it since I cannot have my friend test with it.

**Comment by d0k3** [comment] 2017-03-21 12:23
Well, the current hourly may work as well, but let's continue this in the other issue.

**Comment by Jerry-Shaw** [comment] 2017-03-21 12:23
OK

**Comment by d0k3** [comment] 2017-03-22 10:51
Closing this issue, as it was unique to that console and we have no way of reproducing it. Will be reopened if it will turn up again. Also, @MelonGx - feel free to reopen if you can add anything to it.

**Closed by d0k3** 2017-03-22 10:51 UTC

**Comment by MelonGx** [comment] 2017-03-24 06:00
@d0k3 OK if I engage any other problem similar to this.
