### ISSUE TITLE
Auto CTRNAND Transfer: failed!

### ISSUE THREAD

**Issue by PiclesHavaiano** [d0k3/Decrypt9WIP#140] opened 2017-01-04 00:31 UTC
sorry if i'm on the wrong page ( i'm new here at github ).
So, i was trying to hack my old 3ds ( 11.1.0-34U ) by this guide https://3ds.guide/homebrew-launcher-(soundhax) and i ended up on this: ( this part https://3ds.guide/2.1.0-ctrtransfer )
![what](https://cloud.githubusercontent.com/assets/18230562/21628132/4c38a260-d204-11e6-9417-b460366577dd.jpg)
any ideas?

**Comment by khang06** [comment] 2017-01-04 00:55
Are you sure you copied it to the right place?

**Comment by PiclesHavaiano** [comment] 2017-01-04 00:57
I followed the guide, exactly as it says in the link and nothing else.

**Comment by PiclesHavaiano** [comment] 2017-01-04 00:58
i didn't see any NATIVE_FIRM file tough

**Comment by mariogamer2** [comment] 2017-01-04 00:58
Did you ever NFIRM downgraded your 3ds? And are you sure about these file?

**Comment by PiclesHavaiano** [comment] 2017-01-04 00:59
never '-' i'm just a random person trying to hack a 3ds and following that guide on the web

**Comment by PiclesHavaiano** [comment] 2017-01-04 01:00
https://3ds.guide/homebrew-launcher-(soundhax)

**Comment by d0k3** [comment] 2017-01-09 14:28
Well... you know this is not for support but rather for bug reports and feature requests? This actually looks like you did something wrong, so I'd suggest you first try to get support in one of the usual places (f.e. #3dshacks on IRC Rizon). If you get this solved, please report back here. If you think the problem is in D9 (and you can tell me why), let me know.

**Comment by olliz0r** [comment] 2017-01-09 23:30
We had two people in the 3ds hacking discord with the same issue, first person rebooted and bricked, second person stayed in d9, and restored the nand backup.

The person that managed to recover said the sd card was 100% full (so 0 bytes free) after the ctr transfer, so maybe that's what caused it, I attached the two decrypt9 logs, but I doubt they'll show anything new.

[Decrypt9 (1).txt](https://github.com/d0k3/Decrypt9WIP/files/694888/Decrypt9.1.txt)
[Decrypt9 (2).txt](https://github.com/d0k3/Decrypt9WIP/files/694889/Decrypt9.2.txt)

**Comment by d0k3** [comment] 2017-01-14 14:19
100% full... what kind of data was on the SD card? Meaning: Was that person at fault for filling it up to the brink themselves, or did something write garbage data?

**Comment by olliz0r** [comment] 2017-01-14 15:54
It was the persons fault, small sd card and filled with other stuff already, maybe they even ended up using some sd checker tool that writes garbage data to test and didn't remove the remains.

It looks like it was enough space to start the ctrtransfer + (maybe) nand backup, but once that was done there was no second check if there's actually enough space left for the full transfer and the sd ran out of space halfway through, possibly causing this error.

**Comment by d0k3** [comment] 2017-01-14 16:01
Okay, then I'll solve this by adding a stricter free space check.

**Comment by d0k3** [comment] 2017-01-14 16:16
Okay, this new version should not allow this error to happen anymore:
https://transfer.sh/YxpYN/decrypt9wip-20170114-161552.zip

If anyone (with a hardmod!) can test this, it is appreciated, this preventing that issue in the future is basically a safe bet, though.

**Comment by d0k3** [comment] 2017-01-15 14:29
Alright... it's rather improbable anyone can help me test this, so I'm closing this now. YOu will have to trust me this can't happen again ;). Release with the bugfix coming up later today.

**Closed by d0k3** 2017-01-15 14:29 UTC
