### ISSUE TITLE
Decrypt9 wont start

### ISSUE THREAD

**Issue by fuba777** [d0k3/Decrypt9WIP#100] opened 2016-10-08 15:28 UTC
Hello,

i followed this guide to install homebrew  a9lh on my ds.

That worked perfectly. In the end i updaded as it was mentioned in the tutorial

Now i cant find decrypt9 in homebrew launcher. If i download last release and copy folder to /3ds/ folder on sd-card i can find decrypt9 in homebrew launcher. When i start, theres only a red screen  -  then a black one and a red screen again. After this i get back to homebrew launcher.

How can i solve this problem?

**Comment by cmdj13** [comment] 2016-10-08 15:35
Download Decrypt9, put the .bin file on your sdcard in the folder SD:/luma/payloads and rename it to left_decrapt9.bin. Now when you hold left when you boot your 3DS, it will start Decrypt9. This method is recommended, only use the HBL method if your console does not have A9LH installed.

**Comment by fuba777** [comment] 2016-10-08 18:20
this worked thanks.

but when i do "NCCH Padgen" i get following error:

Opening seeddb.bin...
Could not open seeddb.bin
9.x seed crypto will fail
Opening ncchinfo.bin ...
Could not open ncchinfo.bin
NCCH Padgen: failed!


What am I doing wrong?

**Comment by mariogamer2** [comment] 2016-10-08 18:24
This mean there is no ncchinfo.bin file on the root of the SD or in D9 work folder...

Also,this is not a forum.

**Comment by fuba777** [comment] 2016-10-08 18:58
but should not this file be put into "Decrypt9" folder?

**Comment by mariogamer2** [comment] 2016-10-08 19:06
Decrypt9 is no more the work folder,see readme... (files9)

**Comment by MelonGx** [comment] 2016-10-09 07:50
HBL Decrypt9WIP hanging on start has been already existed for a long time.
It is caused by HBL's instability.

**Comment by mos6507** [comment] 2016-10-09 14:14
rtfm

> NCCH Padgen: This generates XORpads for NCCH/NCSD files ('.3DS' f.e.) from ncchinfo.bin files. Generate the ncchinfo.bin via the included Python script ncchinfo_gen.py (or ncchinfo_tgen.py for theme packs) and place it into the /files9/ work folder. Use Archshift's XORer to apply XORpads to .3DS files. NCCH Padgen is also used in conjunction with Riku's 3DS Simple CIA Converter. Important Note: Depending on you 3DS console type / FW version and the encryption in your NCCH/NCSD files you may need additional files (see 'Support files' above) and / or seeddb.bin.

Under Miscellaneous..

> Update SeedDB: Use this to create or update the ´seeddb.bin´ file on your SD card with the seeds currently installed in your Sys/EmuNAND. Only new seeds will get added to seeddb.bin, seeds already in the database stay untouched.

**Comment by d0k3** [comment] 2016-10-10 09:21
Oh well, that kind of issue again. RTFM indeed - this is not a support forum. Seeing as this is already solved, too, I'm closing this now.

**Closed by d0k3** 2016-10-10 09:21 UTC
