### ISSUE TITLE
"Ticket not legit" on building self-purchased e-shop contents?

### ISSUE THREAD

**Issue by MelonGx** [d0k3/Decrypt9WIP#127] opened 2016-12-13 12:27 UTC
Why Decrypt9WIP recognize that it isn't legit? I can prove that I have bought it anyway.

Selected: [CIA Builder (SysNAND/orig.)]
0x34 KeyY: set up from NAND

id0 is (snip)
Use arrow keys and A to choose a folder
/title/00040000/00190a00 (*** also happens on 1A0300(Super Mario Maker) etc.)

Building CIA from ID 0004000000190A00
Fetching TMD...
Searching for proper ticket...
Found ticket, injecting...
Console unique info found, wiping...
Ticket not legit, disabling reencrypt...
Writing CIA stub (14656 byte)...
Injecting content id 00000002 (331520 kB)...
Decrypting content id 00000002 (SD)...
Injecting content id 00000003 (1140 kB)...
Decrypting content id 00000003 (SD)...
Finalizing CIA file...

1x generated / 0x failed
CIA Builder (SysNAND/orig.): succeeded!

Press B to return, START to reboot.

**Comment by d0k3** [comment] 2016-12-13 12:44
The problem here is that you most likely still have an illegit ticket for that title in your title.db. As the illegit one is the first it finds, you get that message. I'm looking into it, but apart from making the process of searching for tickets much longer for everyone i don#t really have an idea right now.

**Comment by MelonGx** [comment] 2016-12-13 13:03
This is weird because I cannot find any duplicate tickets on ticket.db, only legitimate ones ...... wait, you meant TITLE.DB but not ticket.db?

**Comment by d0k3** [comment] 2016-12-14 11:23
I'm searching for a solution to this. And, yup, I actually meant the ticket.db, not title.db :). More coming up later.

**Comment by d0k3** [comment] 2016-12-16 02:43
Okay, can you test this? You have to select the TMD file inside the appropriate folder via the A button. The A: drive contains SysNAND titles installed to the SD, the B: drive is for EmuNAND.
https://transfer.sh/bPiPy/godmode9-20161216-024250.zip
(or build from the latest GM9 commit)

**Comment by slyder5597** [comment] 2016-12-16 08:19
Interestingly enough I am having a similar problem, and when I put my ticket.db into GroovyCIA/CDN-FX it's giving me a console ID of 00000000, where as legit downloads are supposed to have a console ID, but even though it was downloaded directly from the eshop, this one title doesn't have an ID, and a title I downloaded just before that does. I tried deleting the original download, reinstalling, then dumping a new ticket.db, but it didn't help. For the record, both downloads were UpdatePatches.

**Comment by d0k3** [comment] 2016-12-19 10:49
@slyder5597 (and everyone else reporting these problems - please try the CIA builder in the GM9 build I provided (just select .TMD via A button). GM9 right now contains the most up to date CIA builder and should fix all known problems while providing even faster processing speeds.

**Comment by MelonGx** [comment] 2016-12-21 03:59
@d0k3
Built CIA with [A:] SysNAND SD/title/00040000/00190a00/content/00000000.tmd -> TMD file options... -> Build CIA (standard).
Build CIA (legit) also works.
No "not legit" message popped up.

**Comment by d0k3** [comment] 2016-12-28 16:47
So, MelonGx, does the CIA build with GM9 work as intended? Did you check? (you basically only have to install the CIA GM9 created)

**Comment by d0k3** [comment] 2016-12-28 17:00
Oh... I just noticed something. We wipe personal info from that CIA, right? If we do, we make the ticket illegit (no way around). There are legit tickets without personal info (preinstalled stuff, system stuff), but that does not apply to purchases.

In short: use GM9 for this for now. I may add something for it into D9 later, but I'm not sure atm. Actually, with all the good, new stuff the GM9 CIA builder brings, the D9 CIA builder is already outdated by now and needs works.

So, you're issue is expecpected, and I'm closing this now. Feel free to reopen if I got anything wrong or open an issue in GM9 if there are any problems with the CIA it created,

**Closed by d0k3** 2016-12-28 17:00 UTC
