### ISSUE TITLE
Decrypt9WIP all-in-one 20160505 "Health&Safety Dump" Fails

### ISSUE THREAD

**Issue by PrickyRex** [d0k3/Decrypt9WIP#51] opened 2016-05-06 04:14 UTC
So when I try to dump Health & Safety it tells me that the dump failed! It still creates a hs.app on my SD , but I'm skeptical of it. I think the reason it fails is because I have FBI already injected and the verification fails therefore the whole process just fails. I just want to update FBI. I never had issues with previous versions. Log is attached if it's any help. Thanks!
[Decrypt9.txt](https://github.com/d0k3/Decrypt9WIP/files/251532/Decrypt9.txt)

**Comment by d0k3** [comment] 2016-05-06 08:14
I recently had to fix some stuff in the NCCH encryptor / decryptor, which may or may not be the cause of this. You may also have used rxTools injection at some point. Long story short: Just use this hs.app to create the new FBI_with_banner.app, inject that, and you won't have any comparable problems in the future.

Also, give me feedback after you did it!

**Comment by PrickyRex** [comment] 2016-05-06 08:30
I have never actually used rxTools, but I did create and inject a new FBI_with_banner.app with the "failed" hs.app dump and after I injected it seems like Iv'e sucessfully updated to FBI 2.2.1. Thanks!

**Comment by d0k3** [comment] 2016-05-06 09:07
Alright, closing this now...

**Closed by d0k3** 2016-05-06 09:07 UTC
