### ISSUE TITLE
Building key database behaving strangely, maybe?

### ISSUE THREAD

**Issue by NinjaBoyLao** [d0k3/Decrypt9WIP#102] opened 2016-10-16 08:37 UTC
basically d9 is just not wanting to work with the "aeskeydb.bin" that was in The Guide, and i had to delete it via insertion into card reader before it would start adding keys again. CTRXplorer wouldn't delete it either, it just kept saying error: cant delete file, like it didn't exist or something. FBI said the same thing.

**Comment by d0k3** [comment] 2016-10-17 08:48
This is a problem with your SD card and/or file system, not with D9. CTRXplorer and FBI not being able to delete that file prove this. I suggest you check your SD card via chkdsk (or equivalent, and no help on this provided here, ask elsewhere).

Closing this now...

**Closed by d0k3** 2016-10-17 08:48 UTC

**Comment by NinjaBoyLao** [comment] 2016-10-24 11:41
might it be an issue with cluster size? i don't know how sd cards work but you mentioned going back to the original cluster sizing in a release recently, and i dont think ive ever formatted back to whatever the original was. windows error checking said the sd card was fine, and there aren't any scratches on the contacts. i know you said no help and im really sorry i just don't know what else could be going wrong since everything else reads fine and i havent had any weird behavior from anything, stock games or brewed apps.

**Comment by d0k3** [comment] 2016-10-24 12:29
This has nothing to do with cluster size. There is an error in the file system, which may be caused by hardware. Format that SD card fresh (use E9 or a recent build, not release of GM9). Otherwise more problems will pop up later. Better alternative would be using a different SD card.
