### ISSUE TITLE
Booting from HBC with 20161021 with fresh downgrade 9.2.0-20U from 10.7.0-33U n3DS results in blackscreen.

### ISSUE THREAD

**Issue by Nakihabara** [d0k3/Decrypt9WIP#106] opened 2016-10-22 22:44 UTC
I was a handheld previously on 10.7U and downgraded to 9.2U as per Plailect's guide would have you do so. I have tried about 20 or so times to launch the 20161021 build and it would just blackscreen. I used 20161015 and it worked first try. I've done NAND dumps on 3 other systems within the past week and this was the only handheld that gave issues with running Decrypt9WIP and I'm just assuming that something might be up in this latest version as it just refused to work or I'm just unlucky. Really don't know where else to leave comments so I thought this might be helpful or useful in some way.

**Comment by MelonGx** [comment] 2016-10-23 08:20
HBL version of Decrypt9WIP's instability is a known issue.
It's caused by HBL but not Decrypt9WIP.
Use either MSET or A9LH for 100% entry.

**Comment by MelonGx** [comment] 2016-10-23 08:32
Use Downgrade Check 2.0 by zoogie to check if your N3DS has a frankenfirmware.

**Comment by pbanj** [comment] 2016-10-25 02:50
it doesnt always result in a partial on first try. but it does sound like this guy has a partial and needs to run the downgrade again

**Comment by pbanj** [comment] 2016-10-25 03:02
few things
it doesnt always fail. so you saying it does it 100% of the time is wrong.
if he had a partial d9 wouldnt boot at all, the fact the older one is booting means its fine.
every downgrade is frakenfirm because some things didnt exist to be downgraded, that doesnt mean they cause issue.

**Comment by Coaleb2** [comment] 2016-10-31 03:24
I am having the same issue and I have downgraded many many times trying to get this issue fixed I am using the newest decrypt9 and nothing works. I have had luma to work but not  decrypt9 .

**Comment by james-d-elliott** [comment] 2016-10-31 20:32
@Coaleb2 try with another SD? I've seen a few people with the blackscreen with certain SD cards.

**Comment by Coaleb2** [comment] 2016-10-31 21:37
Yeah ive tried two of them

**Comment by d0k3** [comment] 2016-11-01 14:18
Problems booting via HBL is nothing new, and it can't be easily fixed right now, except by completely rewriting Brahma (which I'm not capable of).

I suggest you try a more recent build and tell me if the bootup problems persist:
https://transfer.sh/KamnL/decrypt9wip-20161101-141552.zip

**Comment by Coaleb2** [comment] 2016-11-01 20:37
Unfortunately that version is not working either. Is there anyway I can get you more info to help out this bug?

**Comment by d0k3** [comment] 2016-11-02 10:19
You could try if it has to do with payload size (ie. the file size of the .3DSX file). Menaing: try various releases, take note of the file size, check the boot success rates. I suspect boot rate gets worse with growing payloads.

**Comment by Coaleb2** [comment] 2016-11-02 13:46
Just to clarify do you want me to check the payload of the homebrew launcher or decrypt9?

**Comment by d0k3** [comment] 2016-11-02 14:46
I meant the Decrypt9WIP.3dsx. I think the boot failure rate will be higher if this file is of bigger size. To get different size Decrypt9WIP.3dsx files, you will need to use various releases, ofc.

**Comment by Coaleb2** [comment] 2016-11-02 14:54
Okay I will try that then and report the results to you when I can.

**Comment by d0k3** [comment] 2016-12-28 16:43
Okay, this issue has been open for some time, so can anyone give me some information on the state of this issue? Is this still relevant?

**Comment by d0k3** [comment] 2016-12-28 16:48
Also, everyone running into this issue, thsi may be due to a partial downgrade. Run 3DSident to check the FIRM version. Is it 2.46-0?

**Comment by Nakihabara** [comment] 2016-12-28 17:05
At least for my initial issue, I'm pretty sure you can close this. I'm more than certain that it was caused by HBL's instability and not liking that particular build for whatever reason. Downgrade was fine, FIRM was fine, it was just launching that particular Decrypt9WIP build via HBL that was the only issue.

**Comment by d0k3** [comment] 2016-12-28 18:29
Alright, thank you! Closing this now. Feel free to open another issue if something comes up.

**Closed by d0k3** 2016-12-28 18:29 UTC
